config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :articles
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  def show
    @article = Article.find(params[:id])
  end
  def new
  end
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
  def edit
    @article = Article.find(params[:id])
  end
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  
<div class="container">
    
    <div class="form-group">
      <%= form.label :title %><br>
      <%= form.text_field :title ,class: 'form-control' %>
    </div>
   
    <div class="form-group">
      <%= form.label :text %><br>
      <%= form.text_area :text ,class: 'form-control'%>
    </div>
   
    <p>
    <%= form.submit %>
    <%= link_to 'Back', articles_path , :class => 'btn btn-md btn-danger'%>
  </p>
    </div>
  
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/hola.html.erb
<h1>Edit Article</h1>
 
<%= form_with(model: @article, local: true) do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>







<p>
      <%= form.submit class: 'btn btn-md btn-primary'%>
      <%= link_to 'Back', articles_path , class: 'btn btn-md btn-danger'%>
    </p>

app/views/articles/index.html.erb
<br>
<h1 class="text-center">Listing Articles</h1>

<div class="container">
<%= link_to 'New article', new_article_path, class: 'btn btn-primary text-center' %>
  <div class="row">
    <div class="col-12">
      <table class="table table-bordered">
        <thead class="thead-dark">
          <tr>
            <th>Title</th>
            <th>Text</th>
            <th>Acciones</th>
          </tr>
        </thead>

        <% @articles.each do |article| %>
        <tr>
          <td><%= article.title %></td>
          <td><%= article.text %></td>
          <td><%= link_to 'Show', article_path(article),class: 'btn btn-info'%>
            <%= link_to 'Edit', edit_article_path(article),class: 'btn btn-primary'%>
            <%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } ,class: 'btn btn-danger'%></td>

        </tr>
        <% end %>
      </table>
    </div>
  </div>

</div>

app/views/articles/new.html.erb
<br>
<h1 class="text-center">New Article</h1>
<%= render 'form' %>

  

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
    <h1 class="text-center">Mostrar datos</h1>
      <div class="form-group">
        <label>Title:</label>
        <%= @article.title %>
      </div>
       
      <div class="form-group">
        <label>Text:</label>
        <%= @article.text %>
      </div>
      <%= link_to 'Edit', edit_article_path(@article),class: 'btn btn-primary' %> |
      <%= link_to 'Back', articles_path,class: 'btn btn-primary' %>
      
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRUD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'CRUD', controller: 'articles',class: 'btn btn-primary' %>